name = "RNASplicing"
uuid = "f8c83030-3ca0-4282-a000-447bbf8c9ab1"
authors = ["Zenna Tavares"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
